### ISSUE TITLE
It doesn't work as expected. I didn't receive my pizza.

### ISSUE THREAD

**Issue by valanz** [nicolasheraly/pizzapi#1]
![giphy](https://cloud.githubusercontent.com/assets/254782/10879859/f10bb4a8-8156-11e5-8c34-60afb26dc80b.gif)

**Comment by timothylhuillier** [comment]
![verybadtrip](https://cloud.githubusercontent.com/assets/2414729/10879933/62bd5084-8157-11e5-8c2e-ea487f8ecb49.gif)

**Comment by nicolasheraly** [comment]
@valanz le pizzaiolo @timothylhuillier est en train de la confectionner, il a déjà ajouté la crème !

**Comment by nicolasheraly** [comment]
Now it works as hell !
